# Numpy


#### Install numpy package
#### pip install numpy

In [2]:
pip install numpy

  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)

[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Numpy Tutorial

In [3]:
import numpy as np

# General method of creating arrays

## Array Creation : Conversion from other python structures

In [ ]:

myarr = np.array([[3,6,7],[1,2,3],[3,4,5]], np.float16)

In [18]:
myarr

array([[3, 6, 7],
       [1, 2, 3],
       [3, 4, 5]], dtype=int32)

In [19]:
# shape of array
myarr.shape

(3, 3)

In [21]:
# size
myarr.size

9

In [20]:
# dtype
myarr.dtype

dtype('int32')

In [22]:
# change element ---> myarr[row,col]
myarr[0,1] = 23
myarr


array([[ 3, 23,  7],
       [ 1,  2,  3],
       [ 3,  4,  5]], dtype=int32)

## Intrinsic numpy array creation objects

In [25]:
# check default
zeros = np.zeros((2,3),np.int32)
zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [31]:
# start and stop and dtype
range_arry = np.arange(3,15,dtype=np.int32)
range_arry

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int32)

In [33]:
# linespace

lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [37]:
# empty ==> random value assign 
emp = np.empty((3,3))
emp

array([[1.6426742e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [38]:
# empty_like
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [41]:
# identity
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
ide.shape

(3, 3)

In [48]:
# function to change shape

arr = np.arange(15)

In [52]:
# check the total element
arr = arr.reshape(3,5)

In [53]:
# shape 
arr.shape

(3, 5)

In [55]:
# ravel in 1d array
arr  = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr.shape

(15,)

## Numpy Axis
### 1d -> [1,2,3]
### 2d -> [Axios0(row),Axios1(col)]
            [   
            [1,2,3],
            [2,3,4]
            ]


In [57]:
arr = np.arange(15).reshape(3,5)

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
# sum of each col --> 0+5+10 = 15
arr.sum(axis=0)

array([15, 18, 21, 24, 27])

In [63]:
# sum of each row --> 0+1+2+3+4 = 10
arr.sum(axis=1)

array([10, 35, 60])

In [64]:
# transpose
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [65]:
# flat to itterate
arr.flat

In [66]:
for items in arr.flat:
    print(items)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [67]:
# dimension
arr.ndim

2

In [69]:
# total bytes consumed by data 
arr.nbytes

120

In [70]:
# argmax
one = np.array([1,24,55,9])

In [71]:
# index of highest
one.argmax()

2

In [72]:
# index of lowest
one.argmin()

0

In [74]:
# sort with index is done
one.argsort()


array([0, 3, 1, 2])

In [76]:
# for 2d
arr.argmax(axis=0)

array([2, 2, 2, 2, 2])

### operation


In [81]:
# matrics add
arr1 = np.array([[1,2,3],[2,3,4]])
arr2 = np.array([[2,3,4],[6,7,4]])

# add
print(arr1+arr2)
# mul
print(arr1*arr2)
# sqrt
print(np.sqrt(arr1+arr2))
# max
print(arr1.max())
# min
print(arr1.min())

[[ 3  5  7]
 [ 8 10  8]]
[[ 2  6 12]
 [12 21 16]]
[[1.73205081 2.23606798 2.64575131]
 [2.82842712 3.16227766 2.82842712]]
4
1


In [88]:
arr2

array([[2, 3, 4],
       [6, 7, 4]])

In [90]:
# find element
np.where(arr2>3)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [91]:
np.count_nonzero(arr2)

6

In [92]:

np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [93]:
# check space
import sys

p_ar = [1,3,5]
np_ar = np.array(p_ar)

In [94]:
sys.getsizeof(1)*len(p_ar) #bits

84

In [95]:
np_ar.itemsize * np_ar.size #bits

24

In [96]:
np_ar.tolist()

[1, 3, 5]